(()=>{
  const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
  const C={
    en:{title:'Bn0u0 — Personal Digital Laboratory',desc:'Bn0u0 — projects, systems, games and experiments.',work:'Work',about:'About',profileIndex:'Profile / 001',role:'Independent maker',place:'Taiwan',areas:['Games','Systems','Experiments','Research'],status:'Building ideas into things that can exist.',heroPlace:'Taiwan · 2026',hero:['I build things','I want to exist.'],heroFooter:'Games · Systems · Experiments · Research',scroll:'Scroll to explore',selected:'Selected work',count:'05 selected',open:'Click to open ↗',cursorOpen:'OPEN PROJECT',kicker:'About / 001',manifesto:['I use projects to test ideas,','not to fill a portfolio.'],aboutBody:'This is a living index of worlds, systems and experiments — including the ones that failed, changed direction, or became something else.',aboutTags:['Games','Systems','AI','Quant','Interaction','Experiments'],footer:'BN0U0 / PERSONAL DIGITAL LABORATORY',motto:'Minimal surface. Deep interaction.',top:'Back to top ↑',detailTop:'Selected work / Project detail',close:'Close',closeCursor:'CLOSE',media:'Media / image slot',project:'Project / 001',aria:'Switch language to Chinese'},
    zh:{title:'Bn0u0 — 個人數位實驗室',desc:'Bn0u0 — 遊戲、系統、實驗與研究。',work:'作品',about:'關於',profileIndex:'個人 / 001',role:'獨立創作者',place:'台灣',areas:['遊戲','系統','實驗','研究'],status:'把想法做成真正能存在的東西。',heroPlace:'台灣 · 2026',hero:['我把想法做成東西','讓它們真正存在。'],heroFooter:'遊戲 · 系統 · 實驗 · 研究',scroll:'向下探索',selected:'精選作品',count:'05 精選',open:'點擊開啟 ↗',cursorOpen:'開啟專案',kicker:'關於 / 001',manifesto:['我用專案測試想法，','不是為了填滿作品集。'],aboutBody:'這是一份持續生長的世界、系統與實驗索引——也包含那些失敗、轉向，或最後變成其他東西的專案。',aboutTags:['遊戲','系統','AI','量化','互動','實驗'],footer:'BN0U0 / 個人數位實驗室',motto:'極簡表面。深層互動。',top:'回到頂部 ↑',detailTop:'精選作品 / 專案詳情',close:'關閉',closeCursor:'關閉',media:'媒體 / 圖片區',project:'專案 / 001',aria:'切換語言為英文'}
  };
  const P={
    picnest:{title:'PicNest 2.0',number:'01',year:'2026',start:'2026-02-01',end:'2026-07-03',mediaTitle:'PICNEST 2.0',en:{meta:'Virtual world / Social game',hover:'Exploration, collection, multiplayer presence and Peep personality.',hoverTags:['World','Social'],headline:'A small world designed to feel alive.',description:'Virtual world experiments around exploration, collection, multiplayer presence and Peep personality.',tags:['World','Social','R3F','Systems'],below:'A living-world project focused on discovery, collection and the relationship between players and their Peep.'},zh:{meta:'虛擬世界 / 社交遊戲',hover:'探索、收集、多人存在感與 Peep 個性模擬。',hoverTags:['世界','社交'],headline:'一個被設計成真正有生命感的小世界。',description:'圍繞探索、收集、多人存在感與 Peep 個性所進行的虛擬世界實驗。',tags:['世界','社交','R3F','系統'],below:'一個聚焦於發現、收集，以及玩家與 Peep 關係的生命世界專案。'}},
    quant:{title:'Quant Research System',number:'02',year:'2026',start:'2026-04-01',end:'2026-07-03',mediaTitle:'QUANT RESEARCH SYSTEM',en:{meta:'Research / Trading systems',hover:'Auditable mechanism research, robustness testing and execution controls.',hoverTags:['Python','MT5'],headline:'Research first. Deployment last.',description:'An auditable strategy research pipeline built around mechanism testing, robustness checks and strict separation between research and live execution.',tags:['Python','MT5','Research','Validation'],below:'The emphasis is not on showing a profitable chart. It is on showing how hypotheses survive or fail a repeatable research pipeline.'},zh:{meta:'研究 / 交易系統',hover:'可稽核的機制研究、穩健性測試與執行控制。',hoverTags:['Python','MT5'],headline:'研究優先，部署最後。',description:'一套可稽核的策略研究流程，核心是機制測試、穩健性驗證，以及研究與實盤執行的嚴格分離。',tags:['Python','MT5','研究','驗證'],below:'重點不是展示一張獲利曲線，而是展示假設如何在可重複的研究流程中存活，或被淘汰。'}},
    grass:{title:'Grass Cutting 3min',number:'03',year:'2026',start:'2026-03-01',end:'2026-05-15',mediaTitle:'GRASS CUTTING 3MIN',en:{meta:'Game / Mobile prototype',hover:'Fast sessions, compact systems and a mobile-oriented game loop.',hoverTags:['Game','Mobile'],headline:'A tiny game loop built for immediate play.',description:'A compact mobile-oriented prototype exploring fast sessions, systems design and cross-platform implementation.',tags:['Game','Mobile','Phaser','Prototype'],below:'A short-session game experiment where the constraint is part of the design: interaction should become legible almost immediately.'},zh:{meta:'遊戲 / 行動原型',hover:'快速遊玩、緊湊系統與行動裝置導向的遊戲循環。',hoverTags:['遊戲','行動'],headline:'一個為立即上手而設計的小型遊戲循環。',description:'一個偏向行動裝置的緊湊原型，用來探索短局遊玩、系統設計與跨平台實作。',tags:['遊戲','行動','Phaser','原型'],below:'一個短局遊戲實驗，限制本身就是設計的一部分：互動應該幾乎立刻就能被理解。'}},
    doodle:{title:'Doodle Tyrant',number:'04',year:'2026',start:'2025-10-02',end:'2026-01-18',mediaTitle:'DOODLE TYRANT',en:{meta:'Rogue-lite / Game design',hover:'Merge logic, synergy systems and rough crayon-like art direction.',hoverTags:['Rogue-lite','Design'],headline:'Bad drawings turned into a combat language.',description:'A rogue-lite concept built around merge logic, synergy systems and intentionally rough crayon-like art direction.',tags:['Rogue-lite','Game Design','Systems','Art Direction'],below:'The visual roughness is intentional. The project explores whether an imperfect drawing language can become the identity of the combat system.'},zh:{meta:'Rogue-lite / 遊戲設計',hover:'合成邏輯、協同系統與刻意粗糙的蠟筆美術方向。',hoverTags:['Rogue-lite','設計'],headline:'把拙劣的塗鴉變成一種戰鬥語言。',description:'一個圍繞合成邏輯、協同系統與刻意粗糙蠟筆美術所建立的 Rogue-lite 概念。',tags:['Rogue-lite','遊戲設計','系統','美術方向'],below:'視覺上的粗糙是刻意的。這個專案探索不完美的繪畫語言是否能成為戰鬥系統本身的識別。'}},
    learning:{title:'Learning Games',number:'05',year:'2026',start:'2026-02-18',end:'2026-03-28',mediaTitle:'LEARNING GAMES',en:{meta:'Language / Collection loop',hover:'Listening and repetition redesigned around gacha and collection loops.',hoverTags:['Learning','Product'],headline:'Learning redesigned as collection.',description:'A language-learning game concept using listening, gacha and collection loops to transform repetition into progression.',tags:['Learning','Gacha','Collection','Product'],below:'Instead of presenting study as a task list, the project asks whether collection and progression can make repetition feel naturally motivated.'},zh:{meta:'語言 / 收集循環',hover:'以抽卡與收集循環重新設計聆聽與重複學習。',hoverTags:['學習','產品'],headline:'把學習重新設計成收集。',description:'一個語言學習遊戲概念，利用聆聽、抽卡與收集循環，把重複練習轉換成進度感。',tags:['學習','抽卡','收集','產品'],below:'它不把學習呈現成待辦清單，而是追問：收集與成長能不能讓重複練習自然地產生動機。'}},
    pixel:{title:'Pixel Lab',number:'06',year:'2026',start:'2025-11-12',end:'2026-01-08',mediaTitle:'PIXEL LAB',en:{meta:'Canvas / Physics experiment',hover:'Canvas, physics, sprite processing and interaction experiments.',hoverTags:['Canvas','Physics'],headline:'A technical sandbox for pixels and motion.',description:'Canvas and physics experiments focused on interaction, sprite processing and small technical prototypes.',tags:['Canvas','Physics','Pixel','Experiment'],below:'A lab rather than a single product: a place for small rendering, interaction and sprite-processing experiments.'},zh:{meta:'Canvas / 物理實驗',hover:'Canvas、物理、Sprite 處理與互動實驗。',hoverTags:['Canvas','物理'],headline:'一個用來研究像素與動態的技術沙盒。',description:'聚焦互動、Sprite 處理與小型技術原型的 Canvas 與物理實驗。',tags:['Canvas','物理','像素','實驗'],below:'它更像一間實驗室，而不是單一產品：用來容納小型渲染、互動與 Sprite 處理實驗。'}}
  };
  const formatRange=p=>`${p.start} — ${p.end}`;
  const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)],text=(s,v)=>{const e=q(s);if(e)e.textContent=v};
  const originalDetail=window.__bn0u0DateLayer;
  if(originalDetail)return;
  window.__bn0u0DateLayer=true;
  const css=document.createElement('style');css.textContent=`.project-date{font-size:9px;letter-spacing:.07em;text-transform:uppercase;opacity:.46;white-space:nowrap;margin-left:auto}.detail-date{font-size:9px;letter-spacing:.07em;text-transform:uppercase;color:rgba(242,240,235,.40);white-space:nowrap;margin-left:auto}@media(max-width:900px){.project-date{display:none}}@media(max-width:640px){.detail-date{font-size:8px;width:100%;margin-left:0}}`;document.head.appendChild(css);
  let currentKey='picnest';
  function addRange(item){const key=item.dataset.project,p=P[key];if(!p)return;let node=item.querySelector('.project-date');if(!node){node=document.createElement('span');node.className='project-date';item.querySelector('.project-row')?.appendChild(node)}node.textContent=formatRange(p)}
  function addDetail(){const p=P[currentKey],box=q('.project-detail__number');if(!p||!box)return;let node=box.querySelector('.detail-date');if(!node){node=document.createElement('span');node.className='detail-date';box.appendChild(node)}node.textContent=formatRange(p)}
  function refresh(){qa('.project-item[data-project]').forEach(addRange);addDetail()}
  refresh();
  new MutationObserver(refresh).observe(document.body,{childList:true,subtree:true});
  document.addEventListener('click',e=>{const row=e.target.closest?.('.project-item[data-project] .project-row');if(row){currentKey=row.closest('.project-item')?.dataset.project||currentKey;setTimeout(addDetail,0)}},true);
})();