(()=>{
  const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
  const C={
    en:{title:'Bn0u0 — Personal Digital Laboratory',desc:'Bn0u0 — projects, systems, games and experiments.',work:'Work',about:'About',profileIndex:'Profile / 001',role:'Independent maker',place:'Taiwan',areas:['Games','Systems','Experiments','Research'],status:'Building ideas into things that can exist.',heroPlace:'Taiwan · 2026',hero:['I build things','I want to exist.'],heroFooter:'Games · Systems · Experiments · Research',scroll:'Scroll to explore',selected:'Selected work',count:'05 selected',open:'Click to open ↗',cursorOpen:'OPEN PROJECT',kicker:'About / 001',manifesto:['I use projects to test ideas,','not to fill a portfolio.'],aboutBody:'This is a living index of worlds, systems and experiments — including the ones that failed, changed direction, or became something else.',aboutTags:['Games','Systems','AI','Quant','Interaction','Experiments'],footer:'BN0U0 / PERSONAL DIGITAL LABORATORY',motto:'Minimal surface. Deep interaction.',top:'Back to top ↑',detailTop:'Selected work / Project detail',close:'Close',closeCursor:'CLOSE',media:'Media / image slot',project:'Project / 001',aria:'Switch language to Chinese'},
    zh:{title:'Bn0u0 — 個人數位實驗室',desc:'Bn0u0 — 遊戲、系統、實驗與研究。',work:'作品',about:'關於',profileIndex:'個人 / 001',role:'獨立創作者',place:'台灣',areas:['遊戲','系統','實驗','研究'],status:'把想法做成真正能存在的東西。',heroPlace:'台灣 · 2026',hero:['我把想法做成東西','讓它們真正存在。'],heroFooter:'遊戲 · 系統 · 實驗 · 研究',scroll:'向下探索',selected:'精選作品',count:'05 精選',open:'點擊開啟 ↗',cursorOpen:'開啟專案',kicker:'關於 / 001',manifesto:['我用專案測試想法，','不是為了填滿作品集。'],aboutBody:'這是一份持續生長的世界、系統與實驗索引——也包含那些失敗、轉向，或最後變成其他東西的專案。',aboutTags:['遊戲','系統','AI','量化','互動','實驗'],footer:'BN0U0 / 個人數位實驗室',motto:'極簡表面。深層互動。',top:'回到頂部 ↑',detailTop:'精選作品 / 專案詳情',close:'關閉',closeCursor:'關閉',media:'媒體 / 圖片區',project:'專案 / 001',aria:'切換語言為英文'}
  };
  const P={
    picnest:{title:'PicNest 2.0',number:'01',year:'2026',mediaTitle:'PICNEST 2.0',en:{meta:'Virtual world / Social game',hover:'Exploration, collection, multiplayer presence and Peep personality.',hoverTags:['World','Social'],headline:'A small world designed to feel alive.',description:'Virtual world experiments around exploration, collection, multiplayer presence and Peep personality.',tags:['World','Social','R3F','Systems'],below:'A living-world project focused on discovery, collection and the relationship between players and their Peep.'},zh:{meta:'虛擬世界 / 社交遊戲',hover:'探索、收集、多人存在感與 Peep 個性模擬。',hoverTags:['世界','社交'],headline:'一個被設計成真正有生命感的小世界。',description:'圍繞探索、收集、多人存在感與 Peep 個性所進行的虛擬世界實驗。',tags:['世界','社交','R3F','系統'],below:'一個聚焦於發現、收集，以及玩家與 Peep 關係的生命世界專案。'}},
    quant:{title:'Quant Research System',number:'02',year:'2026',mediaTitle:'QUANT RESEARCH SYSTEM',en:{meta:'Research / Trading systems',hover:'Auditable mechanism research, robustness testing and execution controls.',hoverTags:['Python','MT5'],headline:'Research first. Deployment last.',description:'An auditable strategy research pipeline built around mechanism testing, robustness checks and strict separation between research and live execution.',tags:['Python','MT5','Research','Validation'],below:'The emphasis is not on showing a profitable chart. It is on showing how hypotheses survive or fail a repeatable research pipeline.'},zh:{meta:'研究 / 交易系統',hover:'可稽核的機制研究、穩健性測試與執行控制。',hoverTags:['Python','MT5'],headline:'研究優先，部署最後。',description:'一套可稽核的策略研究流程，核心是機制測試、穩健性驗證，以及研究與實盤執行的嚴格分離。',tags:['Python','MT5','研究','驗證'],below:'重點不是展示一張獲利曲線，而是展示假設如何在可重複的研究流程中存活，或被淘汰。'}},
    grass:{title:'Grass Cutting 3min',number:'03',year:'2026',mediaTitle:'GRASS CUTTING 3MIN',en:{meta:'Game / Mobile prototype',hover:'Fast sessions, compact systems and a mobile-oriented game loop.',hoverTags:['Game','Mobile'],headline:'A tiny game loop built for immediate play.',description:'A compact mobile-oriented prototype exploring fast sessions, systems design and cross-platform implementation.',tags:['Game','Mobile','Phaser','Prototype'],below:'A short-session game experiment where the constraint is part of the design: interaction should become legible almost immediately.'},zh:{meta:'遊戲 / 行動原型',hover:'快速遊玩、緊湊系統與行動裝置導向的遊戲循環。',hoverTags:['遊戲','行動'],headline:'一個為立即上手而設計的小型遊戲循環。',description:'一個偏向行動裝置的緊湊原型，用來探索短局遊玩、系統設計與跨平台實作。',tags:['遊戲','行動','Phaser','原型'],below:'一個短局遊戲實驗，限制本身就是設計的一部分：互動應該幾乎立刻就能被理解。'}},
    doodle:{title:'Doodle Tyrant',number:'04',year:'2026',mediaTitle:'DOODLE TYRANT',en:{meta:'Rogue-lite / Game design',hover:'Merge logic, synergy systems and rough crayon-like art direction.',hoverTags:['Rogue-lite','Design'],headline:'Bad drawings turned into a combat language.',description:'A rogue-lite concept built around merge logic, synergy systems and intentionally rough crayon-like art direction.',tags:['Rogue-lite','Game Design','Systems','Art Direction'],below:'The visual roughness is intentional. The project explores whether an imperfect drawing language can become the identity of the combat system.'},zh:{meta:'Rogue-lite / 遊戲設計',hover:'合成邏輯、協同系統與刻意粗糙的蠟筆美術方向。',hoverTags:['Rogue-lite','設計'],headline:'把拙劣的塗鴉變成一種戰鬥語言。',description:'一個圍繞合成邏輯、協同系統與刻意粗糙蠟筆美術所建立的 Rogue-lite 概念。',tags:['Rogue-lite','遊戲設計','系統','美術方向'],below:'視覺上的粗糙是刻意的。這個專案探索不完美的繪畫語言是否能成為戰鬥系統本身的識別。'}},
    learning:{title:'Learning Games',number:'05',year:'2026',mediaTitle:'LEARNING GAMES',en:{meta:'Language / Collection loop',hover:'Listening and repetition redesigned around gacha and collection loops.',hoverTags:['Learning','Product'],headline:'Learning redesigned as collection.',description:'A language-learning game concept using listening, gacha and collection loops to transform repetition into progression.',tags:['Learning','Gacha','Collection','Product'],below:'Instead of presenting study as a task list, the project asks whether collection and progression can make repetition feel naturally motivated.'},zh:{meta:'語言 / 收集循環',hover:'以抽卡與收集循環重新設計聆聽與重複學習。',hoverTags:['學習','產品'],headline:'把學習重新設計成收集。',description:'一個語言學習遊戲概念，利用聆聽、抽卡與收集循環，把重複練習轉換成進度感。',tags:['學習','抽卡','收集','產品'],below:'它不把學習呈現成待辦清單，而是追問：收集與成長能不能讓重複練習自然地產生動機。'}},
    pixel:{title:'Pixel Lab',number:'06',year:'2026',mediaTitle:'PIXEL LAB',en:{meta:'Canvas / Physics experiment',hover:'Canvas, physics, sprite processing and interaction experiments.',hoverTags:['Canvas','Physics'],headline:'A technical sandbox for pixels and motion.',description:'Canvas and physics experiments focused on interaction, sprite processing and small technical prototypes.',tags:['Canvas','Physics','Pixel','Experiment'],below:'A lab rather than a single product: a place for small rendering, interaction and sprite-processing experiments.'},zh:{meta:'Canvas / 物理實驗',hover:'Canvas、物理、Sprite 處理與互動實驗。',hoverTags:['Canvas','物理'],headline:'一個用來研究像素與動態的技術沙盒。',description:'聚焦互動、Sprite 處理與小型技術原型的 Canvas 與物理實驗。',tags:['Canvas','物理','像素','實驗'],below:'它更像一間實驗室，而不是單一產品：用來容納小型渲染、互動與 Sprite 處理實驗。'}}
  };

  const style=document.createElement('style');
  style.textContent=`.nav{align-items:center}.language-toggle{position:relative;pointer-events:auto;width:72px;height:28px;padding:3px;border:1px solid rgba(255,255,255,.48);border-radius:999px;background:rgba(255,255,255,.05);display:grid;grid-template-columns:1fr 1fr;align-items:center;isolation:isolate;overflow:hidden;letter-spacing:.06em;text-transform:uppercase;font-size:9px;line-height:1;color:#fff;transition:border-color 320ms ease,background 320ms ease,transform 360ms var(--ease)}.language-toggle:hover{border-color:rgba(255,255,255,.82);background:rgba(255,255,255,.1)}.language-toggle:active{transform:scale(.96)}.language-toggle:disabled{opacity:.68}.language-toggle__thumb{position:absolute;z-index:0;left:3px;top:3px;width:31px;height:20px;border-radius:999px;background:#fff;transform:translateX(0);transition:transform 560ms var(--ease)}.language-toggle.is-zh .language-toggle__thumb{transform:translateX(34px)}.language-toggle__option{position:relative;z-index:1;display:grid;place-items:center;height:20px;color:#fff;mix-blend-mode:difference}.language-transition{position:fixed;inset:0;z-index:650;pointer-events:none;overflow:hidden;visibility:hidden}.language-transition__veil{position:absolute;inset:-4%;background:linear-gradient(115deg,#91aaa5 0%,#B4C2BE 42%,#d7e0dd 60%,#78958D 100%);transform:translate3d(-110%,0,0) skewX(-4deg);transition:transform 620ms var(--ease)}.language-transition.is-covering{visibility:visible}.language-transition.is-covering .language-transition__veil{transform:translate3d(0,0,0) skewX(0)}.language-transition.is-leaving .language-transition__veil{transform:translate3d(110%,0,0) skewX(4deg)}body.is-language-switching .profile-card{opacity:0!important;visibility:hidden!important}html[lang="zh-Hant"] body{font-family:Inter,"Noto Sans TC","PingFang TC","Microsoft JhengHei",ui-sans-serif,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}html[lang="zh-Hant"] .hero__title,html[lang="zh-Hant"] .manifesto__statement{letter-spacing:-.055em}@media(max-width:640px){.nav{gap:10px}.language-toggle{width:62px;height:26px}.language-toggle__thumb{width:27px;height:18px}.language-toggle.is-zh .language-toggle__thumb{transform:translateX(28px)}.language-toggle__option{height:18px}.nav a{font-size:10px}}@media(prefers-reduced-motion:reduce){.language-transition{display:none}.language-toggle__thumb{transition:none}}`;
  document.head.appendChild(style);

  const nav=document.querySelector('.nav');
  if(!nav)return;
  const toggle=document.createElement('button');toggle.type='button';toggle.className='language-toggle';toggle.innerHTML='<span class="language-toggle__thumb" aria-hidden="true"></span><span class="language-toggle__option">EN</span><span class="language-toggle__option">中</span>';nav.appendChild(toggle);
  const transition=document.createElement('div');transition.className='language-transition';transition.setAttribute('aria-hidden','true');transition.innerHTML='<div class="language-transition__veil"></div>';document.body.appendChild(transition);

  let lang='en',currentKey='picnest',switching=false;
  try{const saved=localStorage.getItem('bn0u0-language');if(saved==='zh'||saved==='en')lang=saved}catch(e){}
  const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)],text=(s,v)=>{const e=q(s);if(e)e.textContent=v},tags=(s,a)=>{const e=q(s);if(e)e.innerHTML=a.map(x=>`<span>${x}</span>`).join('')};

  function manifesto(lines,instant=true){const root=q('.manifesto__statement');if(!root)return;root.classList.remove('is-flowing');root.textContent='';let i=0;lines.forEach(str=>{const line=document.createElement('span');line.className='manifesto__line';[...str].forEach(ch=>{const c=document.createElement('span');c.className='manifesto__char';c.style.setProperty('--char-index',i++);c.textContent=ch===' '?'\u00A0':ch;line.appendChild(c)});root.appendChild(line)});if(instant||reduced)requestAnimationFrame(()=>root.classList.add('is-flowing'))}

  function row(item,key){const b=P[key],p=b?.[lang];if(!b||!p)return;textIn(item,'.project-row__title',b.title);textIn(item,'.project-row__meta',p.meta);textIn(item,'.project-hover-info__text',p.hover);htmlIn(item,'.project-hover-info__tags',p.hoverTags.map(x=>`<span>${x}</span>`).join(''));textIn(item,'.project-row__action',C[lang].open);const r=item.querySelector('.project-row');if(r){r.dataset.cursor=C[lang].cursorOpen;r.setAttribute('aria-label',lang==='zh'?`開啟 ${b.title} 專案`:`Open ${b.title} project`)}}
  function textIn(root,s,v){const e=root.querySelector(s);if(e)e.textContent=v}function htmlIn(root,s,v){const e=root.querySelector(s);if(e)e.innerHTML=v}

  function detail(key=currentKey){const b=P[key],p=b?.[lang];if(!b||!p)return;currentKey=key;text('.detail-number',b.number);text('.detail-year',b.year);text('.project-detail__title',b.title);text('.project-detail__headline',p.headline);text('.project-detail__description',p.description);tags('.project-detail__tags',p.tags);text('.detail-media-number',b.number);text('.detail-media-title',b.mediaTitle);text('.detail-below-copy',p.below);const media=q('.project-detail__media');if(media)media.dataset.project=key}

  function apply(next,{initial=false}={}){lang=next;const t=C[lang];document.documentElement.lang=lang==='zh'?'zh-Hant':'en';document.title=t.title;q('meta[name="description"]')?.setAttribute('content',t.desc);text('.nav a[href="#work"]',t.work);text('.nav a[href="#about"]',t.about);q('.profile-card')?.setAttribute('aria-label',lang==='zh'?'BN0U0 個人資訊預覽':'BN0U0 profile preview');text('.profile-card__index',t.profileIndex);text('.profile-card__role',t.role);text('.profile-card__location',t.place);tags('.profile-card__areas',t.areas);text('.profile-card__status',t.status);const eye=qa('.hero__eyebrow span');if(eye[0])eye[0].textContent=t.role;if(eye[1])eye[1].textContent=t.heroPlace;const hl=qa('.hero__line>span');if(hl[0])hl[0].textContent=t.hero[0];if(hl[1])hl[1].textContent=t.hero[1];text('.hero__footer p',t.heroFooter);const cue=q('.scroll-cue');if(cue){const a=cue.querySelector('span');cue.childNodes[0].nodeValue=t.scroll+' ';if(a)a.textContent='↓'}const sh=qa('.section-heading p');if(sh[0])sh[0].textContent=t.selected;if(sh[1])sh[1].textContent=t.count;qa('.project-item').forEach(item=>row(item,item.dataset.project));text('.section-kicker',t.kicker);manifesto(t.manifesto,!initial);text('.manifesto__grid>p',t.aboutBody);qa('.manifesto__tags span').forEach((e,i)=>{if(t.aboutTags[i])e.textContent=t.aboutTags[i]});const fp=qa('.site-footer p');if(fp[0])fp[0].textContent=t.footer;if(fp[1])fp[1].textContent=t.motto;text('.site-footer a',t.top);text('.project-detail__top-label',t.detailTop);const close=q('.project-detail__close');const closeTxt=close?.querySelector('span:first-child');if(closeTxt)closeTxt.textContent=t.close;if(close)close.dataset.cursor=t.closeCursor;text('.detail-image-slot',t.media);text('.project-detail__below-label',t.project);detail(currentKey);toggle.classList.toggle('is-zh',lang==='zh');toggle.setAttribute('aria-label',t.aria);toggle.setAttribute('aria-pressed',String(lang==='zh'));try{localStorage.setItem('bn0u0-language',lang)}catch(e){}}

  function swap(){if(switching)return;const next=lang==='en'?'zh':'en';if(reduced){apply(next);return}switching=true;toggle.disabled=true;document.body.classList.add('is-language-switching');transition.classList.remove('is-leaving');transition.classList.add('is-covering');setTimeout(()=>apply(next),360);setTimeout(()=>transition.classList.add('is-leaving'),520);setTimeout(()=>{transition.classList.remove('is-covering','is-leaving');document.body.classList.remove('is-language-switching');toggle.disabled=false;switching=false},1120)}
  toggle.addEventListener('click',swap);
  qa('.project-item').forEach(item=>item.querySelector('.project-row')?.addEventListener('click',()=>{currentKey=item.dataset.project;detail(currentKey)}));
  apply(lang,{initial:true});
})();
